import os

LOCALES = ["en", "de", "nl"]

FOLDER_ASSETS = "assets"
FOLDER_PAGES = "pages"
FOLDER_PARTIALS = "partials"
FOLDER_PUBLISH = "docs"
FOLDER_SOURCES = "sources"
FOLDER_TRANSLATIONS = "translations"

PATH_TO_ASSETS = os.path.join(FOLDER_SOURCES, FOLDER_ASSETS)
PATH_TO_PAGES = os.path.join(FOLDER_SOURCES, FOLDER_PAGES)
PATH_TO_PARTIALS = os.path.join(FOLDER_SOURCES, FOLDER_PARTIALS)
PATH_TO_TRANSLATIONS = os.path.join(FOLDER_SOURCES, FOLDER_TRANSLATIONS)
PATH_TO_PUBLISH = FOLDER_PUBLISH
PATH_TO_SOURCES = FOLDER_SOURCES
